title: Vida
baseurl: "http://danilnagy.github.io/dmc/"

date_format: "%Y-%m-%d"

google_analytics:
disqus_shortname: datamining

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
